### ISSUE TITLE
Unbinned Fit fails with scipy minimizer

### ISSUE THREAD

**Issue by Citiroller** [dsavoiu/kafe2#101]
This fit fails when using the scipy minimizer. It works without problems with iminuit.
```
from kafe2 import UnbinnedContainer, UnbinnedFit, Plot, ContoursProfiler
import numpy as np
import matplotlib.pyplot as plt


def pdf(t, tau=2.2, fbg=0.1, a=1., b=9.75):
    pdf1 = np.exp(-t / tau) / tau / (np.exp(-a / tau) - np.exp(-b / tau))
    pdf2 = 1. / (b - a)
    return (1 - fbg) * pdf1 + fbg * pdf2

# real myon lifetime data
dT = [7.42, 3.773, 5.968, 4.924,  1.468,  4.664,  1.745,  2.144,  3.836,  3.132,
      1.568,  2.352,  2.132,  9.381,  1.484,  1.181,  5.004,  3.06,   4.582,  2.076,
      1.88,   1.337,  3.092,  2.265,  1.208,  2.753,  4.457,  3.499,  8.192,  5.101,
      1.572,  5.152,  4.181,  3.52,   1.344, 10.29,   1.152,  2.348,  2.228,  2.172,
      7.448,  1.108,  4.344,  2.042,  5.088,  1.02,   1.051,  1.987,  1.935,  3.773,
      4.092,  1.628,  1.688,  4.502,  4.687,  6.755,  2.56,   1.208,  2.649,  1.012,
      1.73,   2.164,  1.728,  4.646,  2.916,  1.101,  2.54,   1.02,   1.176,  4.716,
      9.671,  1.692,  9.292, 10.72,   2.164,  2.084,  2.616,  1.584,  5.236,  3.663,
      3.624,  1.051,  1.544,  1.496,  1.883,  1.92,   5.968,  5.89,   2.896,  2.76,
      1.475,  2.644,  3.6,    5.324,  8.361,  3.052,  7.703,  3.83,   1.444,  1.343,
      4.736,  8.7,    6.192,  5.796,  1.4,    3.392,  7.808,  6.344,  1.884,  2.332,
      1.76,   4.344,  2.988,  7.44,   5.804,  9.5,    9.904,  3.196,  3.012,  6.056,
      6.328,  9.064,  3.068,  9.352,  1.936,  1.08,   1.984,  1.792,  9.384, 10.15,
      4.756,  1.52,   3.912,  1.712, 10.57,   5.304,  2.968,  9.632,  7.116, 1.212,
      8.532,  3.000,  4.792,  2.512,  1.352,  2.168,  4.344,  1.316,  1.468, 1.152,
      6.024,  3.272,  4.96,  10.16,   2.14,   2.856, 10.01,   1.232, 2.668, 9.176]

data = UnbinnedContainer(dT)  # create the kafe data object
# create the fit object and set the pdf for the fit
LLfit = UnbinnedFit(data=data, model_density_function=pdf, minimizer='scipy')
# Fix the parameters a and b ...
LLfit.fix_parameter("a", 1)
LLfit.fix_parameter("b", 11.5)
# ...a and limit parameter "fbg"
LLfit.limit_parameter("fbg", (0., 1.))

# assign latex names for the parameters for nicer display
LLfit.assign_parameter_latex_names(t='t', tau=r'\tau', fbg='f', a='a', b='b')
# assign a latex expression for the fit function for nicer display
LLfit.assign_model_function_latex_expression("\\frac{{ (1-{fbg}) \, e^{{-{0}/{tau}}}}}"
                                             "{{{tau}(e^{{-{a}/{tau}}}-e^{{-{b}/{tau}}})}}"
                                             "+ \\frac{{ {fbg} }} {{ {b}-{a} }}")

LLfit.do_fit()  # perform the fit
LLfit.report()  # print a fit report to the terminal

pLL = Plot(LLfit)  # create a plot object
pLL.plot(with_fit_info=True)  # plot the data and the fit
pLL.axes[0]['main'].set_xlabel('Life time '+r'$\tau$'+' (µs)', size='large')  # change the x-axis label

cpfLL = ContoursProfiler(LLfit, profile_subtract_min=False)  # Optional: create a contours profile
cpfLL.plot_profiles_contours_matrix(parameters=['tau', 'fbg'])  # Optional: plot the contour matrix for tau and fbg

plt.show()  # show the plot(s)
```

Traceback:
```
Backend Qt5Agg is interactive backend. Turning interactive mode on.
/home/cedric/Projekte/kafe2/kafe2/core/fitters/nexus.py:1206: UserWarning: Ignoring default value None for function parameter 'parameter_values': non-empty nexus node already exists.
  warnings.warn(
/home/cedric/Projekte/kafe2/kafe2/core/fitters/nexus.py:1206: UserWarning: Ignoring default value None for function parameter 'parameter_constraints': non-empty nexus node already exists.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-62ff85d6ab8a>", line 1, in <module>
    runfile('/home/cedric/Projekte/kafe2/examples/test.py', wdir='/home/cedric/Projekte/kafe2/examples')
  File "/opt/pycharm-professional/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/pycharm-professional/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/cedric/Projekte/kafe2/examples/test.py", line 55, in <module>
    LLfit.do_fit()  # perform the fit
  File "/home/cedric/Projekte/kafe2/kafe2/fit/_base/fit.py", line 667, in do_fit
    self._fitter.do_fit()  # TODO specify other node to minimize
  File "/home/cedric/Projekte/kafe2/kafe2/core/fitters/nexus_fitter.py", line 152, in do_fit
    self._minimize()
  File "/home/cedric/Projekte/kafe2/kafe2/core/fitters/nexus_fitter.py", line 72, in _minimize
    self._minimizer.minimize(max_calls=max_calls)
  File "/home/cedric/Projekte/kafe2/kafe2/core/minimizers/scipy_optimize_minimizer.py", line 244, in minimize
    self._opt_result = opt.minimize(_func,
  File "/usr/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 609, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/usr/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 277, in _minimize_lbfgsb
    raise ValueError('length of x0 != length of bounds')
ValueError: length of x0 != length of bounds
```

Maybe @JohannesGaessler can kook into it, as he has more experience with using the minimizers.

**Comment by Citiroller** [comment]
I've tested the script with multiple revisions dating back to 7e7e3fd, which was before the new Multifit and directly after the new Plot class was introduced.
The error still persists. With that revision scipy seems to use another minimizing alogrithm but with the exact same error message:
```
...
  File "/home/cedric/Projekte/kafe2/kafe2/core/fitters/nexus_fitter.py", line 72, in _minimize
    self._minimizer.minimize(max_calls=max_calls)
  File "/home/cedric/Projekte/kafe2/kafe2/core/minimizers/scipy_optimize_minimizer.py", line 173, in minimize
    self._opt_result = opt.minimize(_func,
  File "/usr/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 617, in minimize
    return _minimize_slsqp(fun, x0, args, jac, bounds,
  File "/usr/lib/python3.8/site-packages/scipy/optimize/slsqp.py", line 341, in _minimize_slsqp
    raise IndexError('SLSQP Error: the length of bounds is not '
IndexError: SLSQP Error: the length of bounds is not compatible with that of x0.
```

**Comment by JohannesGaessler** [comment]
Fixed.
The scipy minimizer didn't correctly handle the combination of fixed and bounded parameters.
