### ISSUE TITLE
Saving fit results as a file with `set_bins` method

### ISSUE THREAD

**Issue by a-monsch** [dsavoiu/kafe2#132]
**Describe the bug**
The `to_file` method after a performed fit cannot save the fit as a file (see traceback).

**To Reproduce**

In fact, any code that uses the `set_bins` method can be used. A brief example is shown:
```
import kafe2 as K2

d_ = K2.HistContainer(n_bins=5, bin_range=(0, 10))
d_.set_bins([1, 2, 3, 4, 5])
d_.add_error([0.5, 0.5, 0.5, 0.5, 0.5])


def lin_model(x, a, b):
    return x * a + b


f_ = K2.HistFit(d_, lin_model, cost_function="chi2")
f_.do_fit()
f_.to_file("test_fit", "yml")

```

**Expected behavior**
The `to_file` method is intended to create a `.yml` file, as in the case of fits where `set_bins` was not used.

**Traceback**
```
Traceback (most recent call last):
  File "D:/User/a-monsch/documents/py_random_tests/kafe2_test.py", line 14, in <module>
    f_.to_file("test_fit", "yml")
  File "C:\Program Files\Python38\lib\site-packages\kafe2-2.0.dev0-py3.8.egg\kafe2\fit\_base\fit.py", line 875, in to_file
    super(FitBase, self).to_file(filename=filename, file_format=file_format)
  File "C:\Program Files\Python38\lib\site-packages\kafe2-2.0.dev0-py3.8.egg\kafe2\fit\io\file.py", line 65, in to_file
    _writer_class(self, OutputFileHandle(filename=filename)).write()
  File "C:\Program Files\Python38\lib\site-packages\kafe2-2.0.dev0-py3.8.egg\kafe2\fit\representation\_yaml_base.py", line 25, in write
    self._yaml_doc = self._make_representation(self._kafe_object)
  File "C:\Program Files\Python38\lib\site-packages\kafe2-2.0.dev0-py3.8.egg\kafe2\fit\representation\fit\yaml_drepr.py", line 81, in _make_representation
    _yaml_doc['dataset'] = DataContainerYamlWriter._make_representation(fit.data_container)
  File "C:\Program Files\Python38\lib\site-packages\kafe2-2.0.dev0-py3.8.egg\kafe2\fit\representation\container\yaml_drepr.py", line 172, in _make_representation
    raise YamlWriterException("Manual set bins are not yet supported with kafe2go.")
kafe2.fit.representation._yaml_base.YamlWriterException: Manual set bins are not yet supported with kafe2go.
```

**System:**
 - OS: Ubuntu 18.04, Windows10
 - Python Version: 3.8.1, 3.6.9

**Comment by Citiroller** [comment]
This feature is currently unsupported as each individual datapoint used to fill the histogram is saved as well as the binning.
When loading a hstogram kafe2 currently loads the datapoints and then fills the histogram using the given binning. This is not possible when the bin heights have been set manually.
This is on our to do list for the long term.

**Comment by JohannesGaessler** [comment]
Fixed.
