### ISSUE TITLE
useful additions to IndexedFit 

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#195]
1. IndexedFit: der ist als allg. Interface für komplexe Fits
  sehr nütztlich, z.B. wenn man einen oder mehrere Parametersätze
{p}(i) auf einen neuen  {p'} transformieren möchte. Das kommt
oft vor, wenn Ergebnisse aus einem oder mehreren Fits weiter
verarbeitet werden müssen.
 Ich habe mal ein Beispiel für den Ordner PhyPraKit/examples angehängt.
Bei der grafischen Darstellung hätte ich noch einige Kleinigkeiten.
   * Bei der Darstellung des Modells ist eine durchgezogene Linie
     nicht sinnvoll, weil die Eingebedaten häufig von völlig
     unterschiedlichem Typ sind (z.B. Steigung und Achsenabschnitt
    einer Geraden); da wären einfache horizontale Linien im Bin
    schöner.
   * es wäre schön, wenn man den einzelnen Eingabewerten nicht
    nur einen Index, sondern auch einen Namen zuweisen könnte.
   Ein Beispiel und einen Vergleich kafe2 - phyFit findet man in einem
  Beispiel zu PhyPraKit;  Beispiel_GeomOptik.py

**Comment by JohannesGaessler** [comment]
I've implemented setting axis ticks on the dev branch.
To set strings as axis ticks call `plot.x_ticks = ["a", "b", "c", "d"]`.
Please confirm whether this works as intended.

**Comment by GuenterQuast** [comment]
works only partly; it is ok for Plots without Ratio or residual, but crashes these are enabled via plot(residual=True). Here the crash log:
Traceback (most recent call last):
  File "_test.py", line 94, in <module>
    f1f2Plot.plot(residual=True)
  File "/usr/lib/python3.6/site-packages/kafe2/fit/_base/plot.py", line 1315, in plot
    self._set_axis_labels(_plot_results, axes_keys=_axes_keys)
  File "/usr/lib/python3.6/site-packages/kafe2/fit/_base/plot.py", line 1070, in _set_axis_labels
    _ax.set_xticks(np.arange(len(_x_ticks)), labels=_x_ticks)
  File "/home/quast/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/quast/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
TypeError: set_ticks() got an unexpected keyword argument 'labels'
